@startuml
left to right direction
actor Guest as guest
package ExerciseLooper {

  usecase "List Exercise" as ListExercise
  usecase "Create Exercise" as CreateExercise
  usecase "Create Question" as CreateQuestion
  usecase "Delete Exercise" as DeleteExercise
  usecase "Delete Question" as DeleteQuestion
  usecase "Answer Question" as AnswerQuestion
  usecase "View Stats" as ViewStats

}
guest-->ListExercise
guest-->CreateExercise
CreateExercise ..>CreateQuestion : Include
guest-->DeleteExercise
CreateQuestion-->DeleteQuestion
ListExercise ..> ViewStats : Extends
ListExercise ..> AnswerQuestion : Extends
@enduml